### ISSUE TITLE
Output File Usage Unclear 

### ISSUE THREAD

**Issue by Aeusman** [Vaa3D/v3d_external#3]
Hi!

First time user here, but I'm a little confused on the usage of the -o flag in vaa3d. When I open a file in the program and save it as a tif (for example) everything works fine, but when I attempt to do this over command line with the -o flag (e.g. -o foo.tif), nothing happens.\
Sample call: .vaa3d -i somefile.v3dpbd -o foo.tif

**Comment by XiaoxiaoLiu** [comment]
Vaa3d's command line supports are defined on the plugin functions.
The "vaa3d" executable itself won't directly takes input or output parameters ( although you could do "`vaa3d input.v3draw`" for example to open an imagem or "`vaa3d  input.swc`" to open an swc file).

`vaa3d -h` shows you all the plugins available for you to use.
You can pick the plugin you need, and feed it into the "vaa3d" command line, for example:
`vaa3d  -x convert_file_format -f help`

It will print out the detailed usage command line for that plugin.
So to convert an input image to tif, you probably want to try:
`vaa3d -x convert_file_format -f convert_format -i somefile.v3dpbd -o foo.tif`
Hope this helps.

**Comment by Aeusman** [comment]
Ah, that makes more sense, thanks!
