### ISSUE TITLE
Vaa3D crashes on ubuntu when loading invalid 3D tiff image

### ISSUE THREAD

**Issue by lsqshr** [Vaa3D/v3d_external#4]
I occasionally was trying to load a broken 3D tiff into v3d today. The tiff image has 2D slices of different sizes by mistake. However V3D crashed on ubuntu16 after outputing:

```
My4DImage::loadImage() calling Image4DSimple::loadImage() with b_useMylib= false 
The current input file has the suffix [tif]
Image4DSimple::loadImage loading filename=[/home/siqi/hpc-data1/Data/Gold166-JSON/mousergc/8.v3draw.tif]
Now try to use LIBTIFF (slightly revised by PHC) to read the TIFF/LSM...


Error in TIFF library:
   Images of stack are not of the same dimensions!
Segmentation fault (core dumped)
```

It seems this error was not correctly handled. Is it a known issue?

**Comment by berl** [comment]
As far as I can tell, the code in question (mg_image_lib.cpp L562 and a couple other lines ) just writes the error text to stderr but doesn't break from the loop reading in the .tif images.
@lsqshr can you provide me with the image to test?
@hanchuan  I think we should just stop reading the .tif and return 0 in this case (or the similar case where a single plane is a different type).  What do you think?

**Comment by lsqshr** [comment]
@berl Thanks for your attention. I just made [a small tiff](https://drive.google.com/open?id=0B5ubdNxmuTU4UE5ySVpWc29mRk0)
 which can reproduce this bug. 
In this tiff, I firstly appended some small slices and then larger slices.
It seems OK if the larger slices come before the smaller ones.

**Comment by berl** [comment]
For the purposes of 3D visualization and analysis, can you describe a use-case for .tif stacks with different size tiles?  Of course the file read should fail fail gracefully instead of crashing and I'll try to track this down; absent a relevant use-case , it's a relatively low priority for use to improve handling of malformed .tif files.

**Comment by lsqshr** [comment]
I don't think malformed tiff are needed in real use cases. However, it is more than easy to make one by mistake. I agree v3d should 'fail gracefully' with malformed inputs.

**Comment by berl** [comment]
fixed.
