### ISSUE TITLE
Clean debugging msg in 3D renderer

### ISSUE THREAD

**Issue by lsqshr** [Vaa3D/v3d_external#8]
The debugging msgs have been there for a long time in 3D renderers.

Here are examples of what I got:
```
wheel pos (x=422.000 y=485.000) viewport (0, 0, 698, 698)
before mouseReleaseEvent _appendMarkerPos
hello after processHit
hello before processHit
```

Would it be nice to clean them? They mess up with the plugin terminal outputs sometimes.

**Comment by zhizhoualan** [comment]
You can comment all these outputs and build Vaa3D for your own version. For
instance, "hello before processHit" and "hello after processHit" could be
commented in /v3d_external/v3d_main/3drenderer/renderer.cpp line 261 and
263.

**Comment by zhizhoualan** [comment]
OK.

I have commented several debugging outputs when hit mouse or wheel. Please
check out the latest code (version 3.223) and try it.

**Comment by lsqshr** [comment]
Much cleaner and satisfying terminal! Thanks Zhi! Closing this!
